### ISSUE TITLE
airstream protective shell doesn't work

### ISSUE THREAD

**Issue by macinati** [Kerbas-ad-astra/Stock-Revamp#20]
I have a problem with the protective shell, as you can see in this video: [https://youtu.be/HsLWj_jPewI](url) I can't use them and I can't change the skin. The debugging console after the video: https://imgur.com/1o18FIv

**Comment by Kerbas-ad-astra** [comment]
Are you using KSP 1.10?  I haven't updated VSR yet.

**Comment by JonnySpruce** [comment]
Can confirm that I'm having the same issue on 1.10. Everything else seems to work as expected. Love the mod!

**Comment by Kerbas-ad-astra** [comment]
Apologies for the delay; I just tested this in KSP 1.10.1, and everything seems to work fine.  Can you check again and get back to me?
