### ISSUE TITLE
Independently Detect VNP and VSR Stock Patches from ModuleManager

### ISSUE THREAD

**Issue by DRVeyl** [Kerbas-ad-astra/Stock-Revamp#22]
During MM patching, I would like to distinguish between the different cases where VNP, VSR stock patches, or both are installed.  Currently, everything is in the VenStockRevamp folder, so there are no additional options for a `NEEDS` test that I am aware of.

Could you make a pair of empty patches that declare passes via `FOR[x]` and place appropriately?  Tentatively, `@nothing:FOR[VenNewParts] {}` and `@nothing:FOR[VenStockRevampStock] {}` each placed in separate files in perhaps `\Part Bin\Data\VNP.cfg` and `\Squad\Data\VSR.cfg`.

The patches do not need to apply against anything, just exist for MM to register `VenNewParts` and `VenStockRevampStock` as passes and thus satisfy `NEEDS` tests.

**Comment by 7ranceaddic7** [comment]
You can do this through MM already by targeting the subdirectory.

You can create a patch that uses conditionals with 

[VensStockRevamp\Part?Bin\NewParts] for Ven's New Parts
[VensStockRevamp\Squad] for Ven's Stock Revamp

**Comment by DRVeyl** [comment]
While NEEDS[VenStockRevamp/Squad] seems to work, these do not:
```
[LOG 13:26:20.952] Deleting root node in file RealismOverhaul/RO_SuggestedMods/VSR/RO_VSR_Engines node: @PART[LVT15]:FOR[RealismOverhaul]:NEEDS[VenStockRevamp/Part*] as it can't satisfy its NEEDS
[LOG 13:26:20.953] Deleting root node in file RealismOverhaul/RO_SuggestedMods/VSR/RO_VSR_Engines node: @PART[LVT15]:FOR[RealismOverhaul]:NEEDS[VenStockRevamp/Part*] as it can't satisfy its NEEDS
[LOG 13:26:20.953] Deleting root node in file RealismOverhaul/RO_SuggestedMods/VSR/RO_VSR_Engines node: @PART[LVT15]:FOR[RealismOverhaul]:NEEDS[VenStockRevamp\Part*] as it can't satisfy its NEEDS
[LOG 13:26:20.954] Deleting root node in file RealismOverhaul/RO_SuggestedMods/VSR/RO_VSR_Engines node: @PART[LVT15]:FOR[RealismOverhaul]:NEEDS[VenStockRevamp/Part*Bin] as it can't satisfy its NEEDS
[LOG 13:26:20.954] Deleting root node in file RealismOverhaul/RO_SuggestedMods/VSR/RO_VSR_Engines node: @PART[LVT15]:FOR[RealismOverhaul]:NEEDS[VenStockRevamp\Part*Bin] as it can't satisfy its NEEDS
[LOG 13:26:20.954] Deleting root node in file RealismOverhaul/RO_SuggestedMods/VSR/RO_VSR_Engines node: @PART[LVT15]:FOR[RealismOverhaul]:NEEDS[VenStockRevamp/Part?Bin] as it can't satisfy its NEEDS
[LOG 13:26:20.954] Deleting root node in file RealismOverhaul/RO_SuggestedMods/VSR/RO_VSR_Engines node: @PART[LVT15]:FOR[RealismOverhaul]:NEEDS[VenStockRevamp\Part?Bin] as it can't satisfy its NEEDS
[LOG 13:26:20.954] Deleting root node in file RealismOverhaul/RO_SuggestedMods/VSR/RO_VSR_Engines node: @PART[LVT15]:FOR[RealismOverhaul]:NEEDS[VenStockRevamp/Part.Bin] as it can't satisfy its NEEDS
[LOG 13:26:20.954] Deleting root node in file RealismOverhaul/RO_SuggestedMods/VSR/RO_VSR_Engines node: @PART[LVT15]:FOR[RealismOverhaul]:NEEDS[VenStockRevamp\Part.Bin] as it can't satisfy its NEEDS
[LOG 13:26:20.954] Deleting root node in file RealismOverhaul/RO_SuggestedMods/VSR/RO_VSR_Engines node: @PART[LVT15]:FOR[RealismOverhaul]:NEEDS[VenStockRevamp/Part_Bin] as it can't satisfy its NEEDS
[LOG 13:26:20.954] Deleting root node in file RealismOverhaul/RO_SuggestedMods/VSR/RO_VSR_Engines node: @PART[LVT15]:FOR[RealismOverhaul]:NEEDS[VenStockRevamp\Part_Bin] as it can't satisfy its NEEDS
```

... which suggests :NEEDS cannot take any wildcard.

**Comment by Kerbas-ad-astra** [comment]
I'll see about deleting that space in the next update.

**Comment by 7ranceaddic7** [comment]
@Kerbas-ad-astra 
I've already worked out everything for removing the space last night. Just need to run tests.

**Comment by DRVeyl** [comment]
I will skim the changes and post feedback.  Looks like one CR slipped thru so far (/PartBin/Data/Tanks.cfg)

**Comment by 7ranceaddic7** [comment]
Good grief.  Thanks.
That's what I get for doing it all in GitHub. 🤪
