### ISSUE TITLE
RV-105 variants don't work (KSP 1.11.1)

### ISSUE THREAD

**Issue by Inglonias** [Kerbas-ad-astra/Stock-Revamp#24]
The orthogonal 4 horn variant of the RV-105 RCS block functions as expected. All other variants do not function at all.

**Comment by Inglonias** [comment]
If you want a quick fix, simply removing the model patch and cfg file from the mod restores Squad's functional model and its variants.

**Comment by Kerbas-ad-astra** [comment]
Yep, that's what I'm doing for the next release: https://github.com/Kerbas-ad-astra/Stock-Revamp/commit/96ee0b10ef7f0680f1ebb071485d889de5f9c93d#diff-58d662265d014e37cb85cc2e2a7ade4a71b6712eb2e99c4d6775cbd5864adc7bL311

**Comment by Inglonias** [comment]
neat
